In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", 100)

In [3]:
#df = pd.read_csv("./DATA/y_train.csv")
# truemalade = df[df["_MICHD"] == 1]

In [4]:
# print(f"#of patient with heart desease : {len(truemalade) / len(df) * 100:.2f}%")

In [28]:
# # LazyPredict exploration
# from lazypredict.Supervised import LazyClassifier
# from sklearn.datasets import load_breast_cancer
# from sklearn.model_selection import train_test_split
# from sklearn.utils import all_estimators

import pandas as pd
df_X = pd.read_csv("../data/raw/x_train.csv")


In [37]:
ids = df_X.SEQNO
df_X[ids.isin(ids[ids.duplicated()])].sort_values("SEQNO")

_STATE  FMONTH     IDATE  IMONTH  IDAY  IYEAR  DISPCODE       SEQNO  \
206472      38       1   1192015       1    19   2015      1200  2015000001   
191111      44       7   9282015       9    28   2015      1200  2015000001   
238000       4       1   1252015       1    25   2015      1200  2015000001   
270889      22       6   6232015       6    23   2015      1200  2015000001   
258429      17       2   2272015       2    27   2015      1200  2015000001   
...        ...     ...       ...     ...   ...    ...       ...         ...   
156247      31       9  10032015      10     3   2015      1200  2015017559   
79154       20       2   2062015       2     6   2015      1200  2015017560   
194105      31      11  11182015      11    18   2015      1200  2015017560   
146580      20       2   2062015       2     6   2015      1100  2015017561   
180631      31      11  11172015      11    17   2015      1200  2015017561   

              _PSU  CTELENUM  ...  _PAREC1  _PASTAE1  _LMTACT1  _LMTWRK1  \
206472  2015000001       NaN  ...        9         9       3.0       3.0   
191111  2015000001       NaN  ...        1         1       3.0       3.0   
238000  2015000001       NaN  ...        4         2       3.0       3.0   
270889  2015000001       NaN  ...        4         2       3.0       3.0   
258429  2015000001       NaN  ...        4         2       3.0       3.0   
...            ...       ...  ...      ...       ...       ...       ...   
156247  2015017559       NaN  ...        3         2       3.0       3.0   
79154   2015017560       NaN  ...        9         9       9.0       9.0   
194105  2015017560       NaN  ...        2         2       3.0       3.0   
146580  2015017561       NaN  ...        4         2       3.0       3.0   
180631  2015017561       NaN  ...        3         2       3.0       3.0   

        _LMTSCL1  _RFSEAT2  _RFSEAT3  _FLSHOT6  _PNEUMO2  _AIDTST3  
206472       4.0         1         1       9.0       9.0       2.0  
191111       4.0         1         1       NaN       NaN       2.0  
238000       4.0         1         1       NaN       NaN       1.0  
270889       4.0         1         1       NaN       NaN       1.0  
258429       4.0         2         2       NaN       NaN       1.0  
...          ...       ...       ...       ...       ...       ...  
156247       4.0         1         1       NaN       NaN       2.0  
79154        9.0         9         9       NaN       NaN       NaN  
194105       4.0         1         1       NaN       NaN       2.0  
146580       4.0         1         1       NaN       NaN       2.0  
180631       4.0         1         1       NaN       NaN       1.0  

[323346 rows x 321 columns]

In [6]:
# X_train, X_test, y_train, y_test = train_test_split(df_X.to_numpy(), df_y.squeeze(), test_size=.2,random_state=123)


# classifier = [clf for clf in all_estimators() if (clf[0] == 'LinearSVC')]
# clf = LazyClassifier(verbose=1, ignore_warnings=False, custom_metric=None, classifiers=classifier)
# #print([est[0] for est in all_estimators()])

In [7]:
# models,predictions = clf.fit(X_train, X_test, y_train, y_test)
# print(models)
# #
# # performs poorly, need data preprocessing

In [8]:
# df_X['ALCDAY5']

In [9]:
df = pd.read_csv("./DATA/heart_disease_health_indicators_BRFSS2015.csv")
df

HeartDiseaseorAttack  HighBP  HighChol  CholCheck   BMI  Smoker  \
0                        0.0     1.0       1.0        1.0  40.0     1.0   
1                        0.0     0.0       0.0        0.0  25.0     1.0   
2                        0.0     1.0       1.0        1.0  28.0     0.0   
3                        0.0     1.0       0.0        1.0  27.0     0.0   
4                        0.0     1.0       1.0        1.0  24.0     0.0   
...                      ...     ...       ...        ...   ...     ...   
253675                   0.0     1.0       1.0        1.0  45.0     0.0   
253676                   0.0     1.0       1.0        1.0  18.0     0.0   
253677                   0.0     0.0       0.0        1.0  28.0     0.0   
253678                   0.0     1.0       0.0        1.0  23.0     0.0   
253679                   1.0     1.0       1.0        1.0  25.0     0.0   

        Stroke  Diabetes  PhysActivity  Fruits  Veggies  HvyAlcoholConsump  \
0          0.0       0.0           0.0     0.0      1.0                0.0   
1          0.0       0.0           1.0     0.0      0.0                0.0   
2          0.0       0.0           0.0     1.0      0.0                0.0   
3          0.0       0.0           1.0     1.0      1.0                0.0   
4          0.0       0.0           1.0     1.0      1.0                0.0   
...        ...       ...           ...     ...      ...                ...   
253675     0.0       0.0           0.0     1.0      1.0                0.0   
253676     0.0       2.0           0.0     0.0      0.0                0.0   
253677     0.0       0.0           1.0     1.0      0.0                0.0   
253678     0.0       0.0           0.0     1.0      1.0                0.0   
253679     0.0       2.0           1.0     1.0      0.0                0.0   

        AnyHealthcare  NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  \
0                 1.0          0.0      5.0      18.0      15.0       1.0   
1                 0.0          1.0      3.0       0.0       0.0       0.0   
2                 1.0          1.0      5.0      30.0      30.0       1.0   
3                 1.0          0.0      2.0       0.0       0.0       0.0   
4                 1.0          0.0      2.0       3.0       0.0       0.0   
...               ...          ...      ...       ...       ...       ...   
253675            1.0          0.0      3.0       0.0       5.0       0.0   
253676            1.0          0.0      4.0       0.0       0.0       1.0   
253677            1.0          0.0      1.0       0.0       0.0       0.0   
253678            1.0          0.0      3.0       0.0       0.0       0.0   
253679            1.0          0.0      2.0       0.0       0.0       0.0   

        Sex   Age  Education  Income  
0       0.0   9.0        4.0     3.0  
1       0.0   7.0        6.0     1.0  
2       0.0   9.0        4.0     8.0  
3       0.0  11.0        3.0     6.0  
4       0.0  11.0        5.0     4.0  
...     ...   ...        ...     ...  
253675  1.0   5.0        6.0     7.0  
253676  0.0  11.0        2.0     4.0  
253677  0.0   2.0        5.0     2.0  
253678  1.0   7.0        5.0     1.0  
253679  0.0   9.0        6.0     2.0  

[253680 rows x 22 columns]

In [10]:
y = df.HeartDiseaseorAttack
y

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
         ... 
253675    0.0
253676    0.0
253677    0.0
253678    0.0
253679    1.0
Name: HeartDiseaseorAttack, Length: 253680, dtype: float64

In [11]:
x = df.drop("HeartDiseaseorAttack", axis=1)
x = x.to_numpy()
x.shape


(253680, 21)

In [17]:
import implementations
import gradient_descent
import helpers
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

#x, _, _ = helpers.standardize(x)
#type(x)


In [18]:

# x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=500004)

degrees = (7, 10, 10)

def split_data_rand(y, tx, ratio, seed=1):
    """Randomly split the dataset, based on the split ratio and the given seed."""
    np.random.seed(seed)

    # generate random indices
    num_row = len(y)
    indices = np.random.permutation(num_row)
    index_split = int(np.floor(ratio * num_row))
    index_tr = indices[: index_split]
    index_te = indices[index_split:]

    # create and return splits
    return y[index_tr], tx[index_tr], y[index_te], tx[index_te]

def build_poly(x, degree):
    """polynomial basis functions for input data x, for j=0 up to j=degree."""
    N = x.shape[0]
    poly = np.ones((N,1))
    
    assert degree > 0
    
    if degree == 1:
        return np.c_[poly, x]

    for i in range(1, degree+1):
        poly = np.c_[poly, x**i]
    
    return poly



# max_iters = 1000
# gamma = 0.00008
# init_w = np.ones((x_train.shape[1], ))
# w, loss = implementations.mean_squared_error_gd(y_train, x_train, init_w , max_iters, gamma)
# w

# w, loss = implementations.least_square(y_train, x_train)
# loss

x = build_poly(x, 3)
ratio = 0.8
seed = 155
# split data to train and test
y_train, tx_train, y_test, tx_test = split_data_rand(y, x, ratio, seed)
tx_train.shape
# w, loss = implementations.ridge_regression(y_train, tx_train, 0.001)
# loss

/var/folders/qp/cry709397gb0wwnv8q7scvlc0000gn/T/ipykernel_96841/1854419472.py:30: RuntimeWarning: overflow encountered in power
  poly = np.c_[poly, x**i]


IndexError: index 167413 is out of bounds for axis 0 with size 6

In [ ]:

lambdas = np.linspace(0.00000001, 0.00001, 100)
W_losses = {}
for i, lambda_ in enumerate(lambdas): 
    w, loss = implementations.ridge_regression(y, x, lambda_)
    seuil = 10
    y_pred_classes = (y_pred > seuil).astype(int)
    accuracy = accuracy_score(y, y_pred_classes)
    # print(f"loss for {lambda_} : {loss}")
    W_losses[loss] = (lambda_, accuracy)
    
print(min(W_losses.keys()), "for",  W_losses[min(W_losses.keys())])

NameError: name 'y_pred' is not defined

In [ ]:
y_pred = x.dot(w)

from sklearn.metrics import accuracy_score

seuil = 10
y_pred_classes = (y_pred > seuil).astype(int)
accuracy = accuracy_score(y, y_pred_classes)
print(accuracy, y.shape)

0.9058144118574583 (253680,)


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

model = LogisticRegression()
model.fit(x_train, y_train)
print(model.score(x_test, y_test))
pred = model.predict(x_test)

0.9090586565752129


/Users/francoisdumoncel/anaconda3/envs/ada/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
# Load original data
yb, input_data, ids = helpers.load_csv_data("./DATA/x_train.csv")

In [ ]:
yb 

array([1., 1., 1., ..., 1., 1., 1.])

In [ ]:
ids

array([53, 33, 20, ..., 39, 33, 32])

In [38]:
# Todo : rewrite load csv data from helpers
import numpy as np
def _load_csv_data(data_path, sub_sample=False):
    """Loads data and returns y (class labels), tX (features) and ids (event ids)"""
    y = np.genfromtxt(data_path, delimiter=",", skip_header=1, dtype=str, usecols=1)
    x = np.genfromtxt(data_path, delimiter=",", skip_header=1)
    ids = x[:, 0].astype(int)
    input_data = x[:, 2:]

    # convert class labels from strings to binary (-1,1)
    yb = np.ones(len(y))
    yb[np.where(y == "b")] = -1

    # sub-sample
    if sub_sample:
        yb = yb[::50]
        input_data = input_data[::50]
        ids = ids[::50]

    return yb, input_data, ids

def load_csv_data(x_path, y_path, sub_sample=False):
    """Loads data and returns y (class labels), x (features)"""
    x = np.genfromtxt(x_path, skip_header=1, delimiter=',')
    y = np.genfromtxt(y_path, skip_header=1, dtype=int)
    
    # todo: add sub_sample procedure
    # todo: check for ids ? 
    
    # Sanity check
    assert y.shape == (328135, )
    assert x.shape[0] == y.shape[0] and x.shape[1] == 321
    return x, y

In [119]:
x, y = load_csv_data("../data/raw/x_train.csv", "../data/raw/y_train.csv")

In [113]:
def build_poly(x, degree):
    """polynomial basis functions for input data x, for j=0 up to j=degree.

    Args:
        x: numpy array of shape (N,), N is the number of samples.
        degree: integer.

    Returns:
        poly: numpy array of shape (N,d+1)

    >>> build_poly(np.array([0.0, 1.5]), 2)
    array([[1.  , 0.  , 0.  ],
           [1.  , 1.5 , 2.25]])
    """
    assert degree > 0
    
    poly = x
    for deg in range(2, degree + 1):
        poly = np.c_[poly, np.power(x, deg)]
    one = np.ones([poly.shape[0], 1])
    return np.c_[one, poly]

def add_poly_expansion_on_data_matrix(poly_exp, tX): 
    return np.concatenate((tX, poly_exp), axis=1)

def compute_and_add_poly_expansion(feature, tX, degree=3): 
    return add_poly_expansion_on_data_matrix(build_poly(feature, degree), tX)


In [120]:
t = np.array([[1, 30, 99], [2, 40, 99], [3, 100, 99]])
f = compute_and_add_poly_expansion(t[:, 1], t, degree=2)
x.shape

(328135, 321)

In [122]:
x = compute_and_add_poly_expansion(x[:, 2], x, degree=3)
x.shape

(328135, 328)